base = File.dirname(__FILE__)
require base + '/ast/ast'
require base + '/ast/expression_list'
require base + '/ast/message_send'
require base + '/ast/identifier'
require base + '/ast/self'
require base + '/ast/string_literal'
require base + '/ast/method_def'
require base + '/ast/singleton_method_def'
require base + '/ast/number_literal'
require base + '/ast/require'
require base + '/ast/class_def'
require base + '/ast/block'
require base + '/ast/assign'
require base + '/ast/array'
