require: "object"
require: "class"
require: "enumerable"
require: "array"
require: "true_class"
require: "nil_class"
require: "fancy_spec"

require: "rubinius/object"
require: "rubinius/class"
require: "rubinius/console"
require: "rubinius/array"
require: "rubinius/false_class"
require: "rubinius/string"
require: "rubinius/fixnum"
require: "rubinius/block"
require: "rubinius/system"
require: "rubinius/exception"
