base = File.dirname(__FILE__) + "/fancy_ext/"
require base + "kernel"
require base + "module"
require base + "object"
require base + "fixnum"
require base + "block_env"
require base + "string"
require base + "array"
require base + "true_class"
require base + "nil_class"
require base + "false_class"
require base + "hash"
require base + "exception"

NATIVE = Object.new
