namespace :parser do

  _ = lambda { |file| File.expand_path(file, File.dirname(__FILE__)); }

  lexer_c = file _["lexer.c"] => _["lexer.lex"] do |task|
    Dir.chdir _["."] do
      sh 'flex', '--outfile', task.to_s, '--header-file=lexer.h',
      task.prerequisites.first
    end
  end

  parser_c = file _["parser.c"] => _["parser.y"] do |task|
    Dir.chdir(_["."]) { sh "bison", "--output", task.to_s, "-d", "-v", task.prerequisites.first }
  end

  makefile = file _["Makefile"] => [_["extconf.rb"], lexer_c, parser_c] do |task|
    Dir.chdir(_["."]) { sh 'rbx', task.prerequisites.first }
  end

  task :parser => parser_c
  task :lexer => lexer_c

  task :compile => [makefile, parser_c, lexer_c] do
    sh 'make', '-C', _["."]
  end

  task :clean do
    rm_f lexer_c.to_s
    rm_f parser_c.to_s
    rm_f makefile.to_s
    rm_f _["lexer.h"]
    rm_f _["parser.h"]
    rm_f _["parser.output"]
    rm_f Dir.glob(_["*.{o,so,rbc,log}"])
    sh 'make', '-C', _["."], "clean" rescue nil
  end

  task :default => :compile

  task :test => "^default" do
    sh _['../../bin/fancy'], _['../../tests/rbx_examples_eval.fy']
  end

end

task :default => "parser:default"
task :clean => "parser:clean"
