#line 2 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.c"

#line 4 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 55
#define YY_END_OF_BUFFER 56
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[186] =
    {   0,
       51,   51,   56,   54,   51,   53,   23,   54,   50,   49,
       23,   54,   10,   11,   23,   45,   23,   48,   23,    6,
        6,   47,   46,   23,   22,   54,   41,   41,   15,   54,
       16,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       13,   19,   14,   51,   23,   40,    0,    8,    0,   50,
       23,   39,   37,   38,   37,   43,   43,   43,    0,    0,
       43,    0,    6,   21,    0,   23,   40,   23,    0,    6,
        0,    0,    0,    0,   17,   20,   37,    0,   12,   41,
       41,   38,    0,    0,   52,   18,   39,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   23,    8,    0,

       43,   43,   43,   43,   43,    0,   43,   44,    7,    5,
        4,    3,   37,   37,    0,   37,   37,   37,    2,   37,
       37,   37,   37,   37,   37,   37,   37,   27,   23,    0,
        0,    0,   43,   43,   43,   42,   36,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   34,   37,    0,   43,
       43,   43,   42,   42,    0,   28,    1,   37,   35,   37,
       37,   37,   30,   37,   31,    9,   37,   37,   37,   37,
       25,   29,   32,   37,   37,   37,   37,   26,   37,   33,
       37,   37,   37,   24,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    4,    8,    9,   10,
       11,    8,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,    4,   26,   27,   28,   27,   27,   27,   27,
       29,   29,   29,   29,   29,   30,   29,   29,   31,   29,
       29,   29,   29,   29,   29,   29,   29,   32,   29,   29,
       33,   34,   35,    4,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   43,   43,   46,   47,   48,
       49,   50,   51,   52,   53,   54,   55,   56,   43,   57,
       58,   43,   59,   60,   61,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[62] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    4,    1,    5,
        1,    3,    1,    3,    1,    3,    6,    6,    6,    6,
        7,    1,    3,    3,    3,    8,    9,    9,   10,   10,
       10,   10,   11,    1,    1,   12,   13,   13,   13,   13,
       13,   13,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   15,   16,
        1
    } ;

static yyconst flex_int16_t yy_base[201] =
    {   0,
        0,    0,  400,  813,  391,  813,   58,   58,    0,  813,
       89,  122,  813,  813,   59,  813,   70,  813,   92,  168,
      103,  813,  813,   61,  146,   39,  222,  255,  813,  388,
      364,  288,   27,  347,  342,  348,  331,  339,   78,  315,
      813,  306,  813,  363,  149,  813,  106,  358,  355,    0,
      197,  813,    0,  813,    0,  321,  378,    0,  435,  316,
        0,  290,  161,  225,  332,  258,  327,  291,  172,  237,
       67,  110,    0,  267,  813,  345,  492,   65,  813,  336,
      335,  318,  130,  335,  813,  813,  813,   78,  299,  292,
      284,  277,   92,   98,  284,  278,  269,  316,  813,  161,

        0,    0,    0,    0,    0,  297,  348,  306,  300,  150,
      197,    0,  525,    0,  347,  280,  271,  255,    0,  269,
      258,  238,  239,  235,  172,  247,  247,    0,  267,  189,
      270,  262,    0,  458,    0,  558,    0,  220,  208,  207,
      207,  207,  201,  195,  174,  179,    0,  176,  214,    0,
        0,    0,  591,    0,  197,    0,    0,  166,    0,  156,
      169,  151,    0,  154,    0,  813,  140,  152,  130,  136,
      139,    0,    0,  110,  123,   96,   69,  813,   58,    0,
       47,   38,   21,    0,  813,  627,  643,  657,  669,  683,
      689,  703,  711,  724,  738,  749,  760,  772,  784,  798

    } ;

static yyconst flex_int16_t yy_def[201] =
    {   0,
      185,    1,  185,  185,  185,  185,  185,  186,  187,  185,
      188,  189,  185,  185,  190,  185,  190,  185,  191,  185,
      185,  185,  185,  192,  185,  193,  194,  194,  185,  195,
      185,  188,   32,   32,   32,   32,   32,   32,   32,   32,
      185,  185,  185,  185,  185,  185,  186,  185,  186,  187,
       32,  185,   32,  185,   32,  189,  185,   56,  189,  185,
       57,  185,  185,  185,  191,  191,  191,  191,  185,  185,
      185,  185,  196,  185,  185,  185,  197,  193,  185,   28,
       28,  185,  186,  195,  185,  185,  185,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,  198,  185,  199,

       57,   57,   57,   57,   57,   59,   56,  191,  185,  185,
      185,  196,  197,  113,  185,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,  198,  199,
      185,  199,  107,   57,  134,  200,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,  185,  134,
      134,  134,  200,  153,  185,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,  185,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,  185,   32,   32,
       32,   32,   32,   32,    0,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185

    } ;

static yyconst flex_int16_t yy_nxt[875] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       22,   23,   24,   25,    7,   26,   27,   27,   27,   28,
       27,   27,   29,   30,   31,   32,   32,   32,   33,   34,
       32,   35,   32,   32,   32,   32,   36,   32,   32,   37,
       32,   38,   39,   40,   32,   32,   32,   32,   41,   42,
       43,   45,   48,   88,   78,   45,  184,   46,   46,   45,
       46,   45,   89,   45,  183,   63,   63,   63,   63,   46,
       45,   45,   45,  110,  110,  182,   63,   63,   63,   63,
      185,   49,   51,   75,   64,   66,   51,   79,   52,   66,

       51,   67,   51,   66,   51,   66,  181,   68,  180,   54,
       99,   51,   51,   51,   66,   66,   66,   69,   95,   70,
       70,   70,   70,  185,   55,   56,  111,  111,  111,   57,
      116,  117,   96,   56,   48,   56,  122,   56,   74,   49,
      123,  179,   58,  178,   56,   56,   56,   59,  124,   45,
      177,  125,   45,   45,   60,   46,   45,   45,   46,   45,
       45,   45,   45,   49,   45,  131,  110,  110,   45,   45,
       76,   45,   45,   45,  176,   69,  175,   70,   70,   70,
       70,   62,   69,  174,   70,   70,   70,   70,  109,  109,
      109,  109,  173,  131,  132,   71,   74,  172,   72,   73,

       51,  171,  170,   74,   51,   71,   52,  169,   51,  168,
       51,  167,   51,  111,  111,  111,   72,  115,  166,   51,
       51,   51,  132,  145,   73,   80,  146,  165,   45,   80,
      164,  163,   45,   80,   46,   80,   45,   80,   45,  162,
       45,  161,   82,  160,   80,   80,   80,   45,   45,   45,
      159,   69,  158,   70,   70,   70,   70,   80,   80,   83,
      157,   66,   80,  156,  185,   66,   80,   67,   80,   66,
       80,   66,   74,   68,  149,   82,   46,   80,   80,   80,
       66,   66,   66,   70,   70,   70,   70,  148,  147,  144,
       80,   55,  143,  142,   66,   55,  141,   87,   66,   55,

       67,   55,   66,   55,   66,  140,   68,  139,   54,  138,
       55,   55,   55,   66,   66,   66,  109,  109,  109,  109,
      137,  108,  185,   55,   56,   46,  128,  127,   57,  126,
      121,  120,   56,  119,   56,  118,   56,   85,  115,  185,
      185,   58,  108,   56,   56,   56,   59,  108,   45,  107,
       58,  133,   45,   60,   46,  134,   45,  185,   45,  133,
       45,  133,  100,  133,   44,   98,   97,   45,   45,   45,
      133,  133,  133,  136,  136,  136,  136,  136,  136,   94,
       62,  101,   93,  135,   92,  102,   91,   90,   86,  101,
       85,  101,   44,  101,  103,  103,  103,  103,   58,  185,

      101,  101,  101,   59,  103,  103,  103,  103,  103,  103,
       60,  185,  185,  104,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  185,   62,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      106,  150,  185,  185,  185,  151,  185,  185,  185,  150,
      185,  150,  185,  150,  185,  185,  185,  185,  185,  185,
      150,  150,  150,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  152,  185,  113,  185,  185,  185,  113,

      185,   87,  185,  113,  185,  113,  185,  113,  185,  185,
      185,  185,  185,  185,  113,  113,  113,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  113,  113,  185,
      185,  185,  113,  185,   87,  185,  113,  185,  113,  185,
      113,  185,  185,  185,  185,  185,  185,  113,  113,  113,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      113,  153,  185,  185,  185,  153,  185,  185,  185,  153,
      185,  153,  185,  153,  185,  185,  185,  185,  155,  185,
      153,  153,  153,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  153,  153,  185,  185,  185,  153,  185,

      185,  185,  153,  185,  153,  185,  153,  185,  185,  185,
      185,  155,  185,  153,  153,  153,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  153,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   50,  185,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   53,
       53,   53,   53,   53,  185,   53,   53,  185,   53,   53,
       53,   61,   61,  185,  185,   61,   61,  185,  185,   61,
       61,   61,   61,  185,   61,   45,   45,   45,   45,   65,
      185,   65,   65,   65,   65,   65,   65,   65,   65,   65,

       65,   65,   65,   65,   65,   45,   45,   45,  185,  185,
      185,  185,  185,   45,   77,  185,  185,  185,   77,  185,
      185,  185,   77,   77,   77,   77,   81,   81,  185,   81,
       81,  185,   81,   81,  185,   81,   81,   81,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,  112,  185,  185,  112,  185,  185,
      185,  112,  114,  114,  114,  114,  185,  185,  114,  114,
      185,  114,  114,  114,  129,  129,  129,  185,  185,  185,
      185,  185,  185,  129,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,

      154,  154,  185,  154,  154,  185,  154,  154,  185,  154,
      154,  154,    3,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185
    } ;

static yyconst flex_int16_t yy_chk[875] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    7,    8,   33,   26,    7,  183,    7,   15,    7,
       24,    7,   33,    7,  182,   15,   15,   15,   15,   17,
        7,    7,    7,   71,   71,  181,   17,   17,   17,   17,
       78,    8,   11,   24,   17,   19,   11,   26,   11,   19,

       11,   19,   11,   19,   11,   19,  179,   19,  177,   11,
       47,   11,   11,   11,   19,   19,   19,   21,   39,   21,
       21,   21,   21,   78,   11,   12,   72,   72,   72,   12,
       88,   88,   39,   12,   83,   12,   93,   12,   21,   47,
       93,  176,   12,  175,   12,   12,   12,   12,   94,   25,
      174,   94,   45,   25,   12,   25,   45,   25,   45,   25,
       45,   25,   45,   83,   45,  100,  110,  110,   25,   25,
       25,   45,   45,   45,  171,   63,  170,   63,   63,   63,
       63,   12,   20,  169,   20,   20,   20,   20,   69,   69,
       69,   69,  168,  130,  100,   20,   63,  167,   20,   20,

       51,  164,  162,   20,   51,   20,   51,  161,   51,  160,
       51,  158,   51,  111,  111,  111,   20,  155,  149,   51,
       51,   51,  130,  125,   20,   27,  125,  148,   64,   27,
      146,  145,   64,   27,   64,   27,   64,   27,   64,  144,
       64,  143,   27,  142,   27,   27,   27,   64,   64,   64,
      141,   70,  140,   70,   70,   70,   70,   27,   28,   28,
      139,   66,   28,  138,  132,   66,   28,   66,   28,   66,
       28,   66,   70,   66,  131,   28,  129,   28,   28,   28,
       66,   66,   66,   74,   74,   74,   74,  127,  126,  124,
       28,   32,  123,  122,   68,   32,  121,   32,   68,   32,

       68,   32,   68,   32,   68,  120,   68,  118,   32,  117,
       32,   32,   32,   68,   68,   68,  109,  109,  109,  109,
      116,  108,  106,   32,   56,   98,   97,   96,   56,   95,
       92,   91,   56,   90,   56,   89,   56,   84,   82,   81,
       80,   56,   67,   56,   56,   56,   56,   65,   76,   62,
       60,  107,   76,   56,   76,  107,   76,   49,   76,  107,
       76,  107,   48,  107,   44,   42,   40,   76,   76,   76,
      107,  107,  107,  115,  115,  115,  115,  115,  115,   38,
       56,   57,   37,  107,   36,   57,   35,   34,   31,   57,
       30,   57,    5,   57,   57,   57,   57,   57,   57,    3,

       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,    0,    0,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,    0,   57,   59,    0,
        0,    0,    0,    0,    0,    0,   59,    0,   59,    0,
       59,    0,    0,    0,    0,   59,    0,   59,   59,   59,
       59,  134,    0,    0,    0,  134,    0,   59,    0,  134,
        0,  134,    0,  134,    0,    0,    0,    0,    0,    0,
      134,  134,  134,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  134,   59,   77,    0,    0,    0,   77,

        0,   77,    0,   77,    0,   77,    0,   77,    0,    0,
        0,    0,    0,    0,   77,   77,   77,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   77,  113,    0,
        0,    0,  113,    0,  113,    0,  113,    0,  113,    0,
      113,    0,    0,    0,    0,    0,    0,  113,  113,  113,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      113,  136,    0,    0,    0,  136,    0,    0,    0,  136,
        0,  136,    0,  136,    0,    0,    0,    0,  136,    0,
      136,  136,  136,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  136,  153,    0,    0,    0,  153,    0,

        0,    0,  153,    0,  153,    0,  153,    0,    0,    0,
        0,  153,    0,  153,  153,  153,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  153,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  187,    0,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  188,
      188,  188,  188,  188,    0,  188,  188,    0,  188,  188,
      188,  189,  189,    0,    0,  189,  189,    0,    0,  189,
      189,  189,  189,    0,  189,  190,  190,  190,  190,  191,
        0,  191,  191,  191,  191,  191,  191,  191,  191,  191,

      191,  191,  191,  191,  191,  192,  192,  192,    0,    0,
        0,    0,    0,  192,  193,    0,    0,    0,  193,    0,
        0,    0,  193,  193,  193,  193,  194,  194,    0,  194,
      194,    0,  194,  194,    0,  194,  194,  194,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  196,    0,    0,  196,    0,    0,
        0,  196,  197,  197,  197,  197,    0,    0,  197,  197,
        0,  197,  197,  197,  198,  198,  198,    0,    0,    0,
        0,    0,    0,  198,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,

      200,  200,    0,  200,  200,    0,  200,  200,    0,  200,
      200,  200,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[56] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
#line 2 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
#include "ruby.h"
#include "parser.h"

int yyerror(char *s);
#line 739 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 73 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"


#line 929 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 186 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 813 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 75 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return CLASS; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 76 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return DEF; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 77 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  yylval.object = rb_str_new2(yytext);
                  return HEX_LITERAL;
                }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 81 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  yylval.object = rb_str_new2(yytext);
                  return OCT_LITERAL;
                }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 85 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  yylval.object = rb_str_new2(yytext);
                  return BIN_LITERAL;
                }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 89 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  yylval.object = rb_str_new2(yytext);
                  return INTEGER_LITERAL;
                }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 93 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  yylval.object = rb_str_new2(yytext);
                  return DOUBLE_LITERAL;
                }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 97 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  yylval.object = rb_str_new2(yytext);
                  return STRING_LITERAL;
                }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 101 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  yylval.object = rb_str_new2(yytext);
                  return MULTI_STRING_LITERAL;
                }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 105 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return LPAREN; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 106 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return RPAREN; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 107 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return AT_LCURLY; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 108 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return LCURLY; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 109 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return RCURLY; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 110 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return LBRACKET; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 111 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return RBRACKET; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 112 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return LHASH; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 113 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return RHASH; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 114 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return STAB; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 115 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return ARROW; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 116 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return THIN_ARROW; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 117 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return EQUALS; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 118 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  yylval.object = rb_str_new2(yytext);
                  return OPERATOR;
                }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 122 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return RETURN_LOCAL; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 123 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return RETURN; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 124 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return REQUIRE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 125 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return TRY; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 126 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return CATCH; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 127 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return FINALLY; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 128 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return RETRY; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 129 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return SUPER; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 130 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return PRIVATE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 131 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return PROTECTED; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 132 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  yylval.object = rb_str_new2(yytext);
                  return IDENTIFIER;
                }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 136 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  return MATCH;
                }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 139 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  return CASE;
                }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 142 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  yylval.object = rb_str_new2(yytext);
                  return IDENTIFIER;
                }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 146 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  yylval.object = rb_str_new2(yytext);
                  return SELECTOR;
                }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 150 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  yylval.object = rb_str_new2(yytext);
                  return RUBY_SEND_OPEN;
                }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 154 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  yylval.object = rb_str_new2(yytext);
                  return RUBY_OPER_OPEN;
                }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 158 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  yylval.object = rb_str_new2(yytext);
                  return CONSTANT;
                }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 162 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  yylval.object = rb_str_new2(yytext);
                  return CONSTANT;
                }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 166 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  yylval.object = rb_str_new2(yytext);
                  return SYMBOL_LITERAL;
                }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 170 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{
                  yylval.object = rb_str_new2(yytext);
                  return REGEX_LITERAL;
                }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 174 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return COMMA; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 175 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return SEMI; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 176 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return COLON; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 177 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return DOT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 178 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return DOLLAR; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 180 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 182 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 183 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{}
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 184 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ return NL; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 186 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
{ fprintf(stderr, "SCANNER %d", yyerror("")); exit(1);	}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 188 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
ECHO;
	YY_BREAK
#line 1356 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 186 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 186 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 185);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 188 "/home/bakkdoor/projekte/fancy/fancy-lang/lib/parser/ext/lexer.lex"
